### ISSUE TITLE
sundials-3.1.0 doesn't install kinsol/kinsol_lapack.h

### ISSUE THREAD

**Issue by yurivict** [bjodah/pykinsol#5]
```kinsol_cxx.hpp``` wants to include ```kinsol/kinsol_lapack.h```, but there's no such file.

**Comment by bjodah** [comment]
I tried to fix this in gh-6
Would you mind trying again with `master`?

**Comment by yurivict** [comment]
It works now, thank you for fixing.

----

One caveat is that LAPACK isn't a default option in sundials. So I will have to change the default in the lapack port to LAPACK=on, the opposite of what the project defaults to.
Additionally, LAPACK=on forces it to change the index type to SUNDIALS_INDEX_TYPE=int32, and this forces to turn off some other options because they aren't compatible with this index type.
But these aren't your problems, these are the problems of sundials.

**Comment by bjodah** [comment]
What about having `setup.py` look for an environment variable (e.g. `PYKINSOL_NO_LAPACK=1`), have it conditionally define `-DKINSOL_NO_LAPACK` and have some `#ifdef` blocks in `kinsol_cxx.hpp` using sundials own linear algebra routines, would that help?

(it might be a bit of work so no promises how soon I'll be able to add that though)

**Comment by yurivict** [comment]
Fine with me if this works.
